apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-1
  annotations:
    harness.io/primary-service: "true"
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.containerPort }}
  selector:
    app: {{ .Release.Name }}-app
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-2
  annotations:
    harness.io/stage-service: "true"
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.containerPort }}
  selector:
    app: {{ .Release.Name }}-app