apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-1
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.containerPort }}
  selector:
    app: {{ .Release.Name }}-app
